const northShoreBeaches = [
{beachName: "Camp Harold Erdman",	location: "Mokulēʻia"},
{beachName: "Mokulēʻia Army Beach",	location: "Mokulēʻia"},
{beachName: "Mokulēʻia Beach",	location: "Mokulēʻia"},
{beachName: "Makaleha Beach Park",	location: "Mokulēʻia"},
{beachName: "ʻĀweoweo Beach Park",	location: "Waialua"},
{beachName: "Puʻuiki Beach Park",	location: "Waialua"},
{beachName: "Kaiaka Bay Beach Park",	location: "Haleʻiwa"},
{beachName: "Haleʻiwa Aliʻi Beach Park",	location: "Haleʻiwa"},
{beachName: "Haleʻiwa Beach Park",	location: "Haleʻiwa"},
{beachName: "Papaʻiloa Beach",	location: "Kawailoa"},
{beachName: "Laniākea Beach",	location: "Kawailoa"},
{beachName: "Chun's Reef Beach",	location: "Kawailoa"},
{beachName: "Kawailoa Beach",	location: "Kawailoa"},
{beachName: "Leftovers Beach Access Park",	location: "Kawailoa"},
{beachName: "Uppers Surfing Support Park",	location: "Kawailoa"},
{beachName: "Waimea Bay Beach Park",	location: "Waimea Bay"},
{beachName: "Pūpūkea Beach Park",	location: "Pūpūkea"},
{beachName: "Kē Iki Beach Park",	location: "Pūpūkea"},
{beachName: "Banzai Beach",	location: "Pūpūkea"},
{beachName: "The Pipeline",	location: "Pūpūkea"},
{beachName: "ʻEhukai Beach Park",	location: "Pūpūkea"},
{beachName: "Sunset Beach",	location: "Pūpūkea"},
{beachName: "Kaunala Beach",	location: "Pūpūkea"},
{beachName: "Waialeʻe Beach Park",	location: "Waialeʻe"},
{beachName: "Kawela Bay Beach",	location: "Kawela Bay"},
{beachName: "Turtle Bay Beach",	location: "Kahuku"},
{beachName: "Bayview Beach (Kuilima Cove)",	location: "Kahuku"},
{beachName: "Kaihalulu Beach",	location: "Kahuku"},
{beachName: "Hanakaʻīlio Beach",	location: "Kahuku"}
];

const southShoreBeaches = [
{beachName: "Queen's Beach (Kaloko Beach)", location: "Koko Head"},
{beachName: "Sandy Beach Park	",location: "Koko Head"},
{beachName: "Eternity Beach (Hālona Cove)	",location: "Koko Head"},
{beachName: "Hanauma Bay Beach Park	",location: "Hawaiʻi Kai"},
{beachName: "Koko Kai Beach Park	",location: "Hawaiʻi Kai"},
{beachName: "Kōkeʻe Beach Park	",location: "Hawaiʻi Kai"},
{beachName: "Portlock Beach	",location: "Hawaiʻi Kai"},
{beachName: "Maunalua Bay Beach Park	",location: "Hawaiʻi Kai"},
{beachName: "Kuliʻouʻou Beach Park	",location: "Hawaiʻi Kai"},
{beachName: "Paikō Beach	",location: "Hawaiʻi Kai"},
{beachName: "Niu Beach	",location: "Hawaiʻi Kai"},
{beachName: "Kawaikuʻi Beach Park	",location: "ʻĀina Haina"},
{beachName: "Wailupe Beach Park	",location: "ʻĀina Haina"},
{beachName: "Kāhala Mandarin Oriental Beach (Kāhala Hilton Beach)	",location: "Kāhala, Honolulu"},
{beachName: "Waiʻalae Beach Park	",location: "Kāhala, Honolulu"},
{beachName: "Kāhala Beach	",location: "Kāhala, Honolulu"},
{beachName: "Kaʻalāwai Beach	",location: "Kaimukī, Honolulu"},
{beachName: "Kuilei Cliffs Beach Park	",location: "Kaimukī, Honolulu"},
{beachName: "Diamond Head Beach Park	",location: "Kaimukī, Honolulu"},
{beachName: "Lēʻahi Beach Park	",location: "Kaimukī, Honolulu"},
{beachName: "Mākālei Beach Park	",location: "Kaimukī, Honolulu"},
{beachName: "Outrigger Canoe Beach	",location: "Kapahulu, Honolulu"},
{beachName: "Kaimana Beach (Sans Souci Beach)	",location: "Kapahulu, Honolulu"},
{beachName: "Queen's Surf Beach Park	",location: "Kapahulu, Honolulu"},
{beachName: "Kūhiō Beach Park (Waikīkī Beach Center)	",location: "Waikīkī, Honolulu"},
{beachName: "Gray's Beach	",location: "Waikīkī, Honolulu"},
{beachName: "Fort DeRussy Beach	",location: "Waikīkī, Honolulu"},
{beachName: "Duke Paoa Kahanamoku Lagoon	",location: "Waikīkī, Honolulu"},
{beachName: "Ala Moana Beach Park	",location: "Ala Moana, Honolulu"},
{beachName: "Kewalo Basin Park	",location: "Ala Moana, Honolulu"},
{beachName: "Kakaʻako Waterfront Park (Point Panic Beach Park)	",location: "Kakaʻako, Honolulu"},
{beachName: "Sand Island State Beach Park	",location: "Sand Island, Honolulu"},
{beachName: "Keʻehi Lagoon Beach Park	",location: "Salt Lake, Honolulu"},
{beachName: "Hickam Harbor Beach	",location: "Hickam Air Force Base"},
{beachName: "Fort Kamehameha Beach	",location: "Hickam Air Force Base"},
{beachName: "Aloha ʻĀina Park	",location: "Hickam Air Force Base"},
{beachName: "ʻAiea Bay State Recreation Area	",location: "ʻAiea"},
{beachName: "Neal S. Blaisdell Park (Pearl Harbor Park)	",location: "Pearl Harbor"},
{beachName: "West Loch Shoreline Park	",location: "Waipahu"},
{beachName: "Iroquois Beach	",location: "ʻEwa Beach"},
{beachName: "ʻEwa Beach Park	",location: "ʻEwa Beach"},
{beachName: "Oneʻula Beach Park	",location: "ʻEwa Beach"},
{beachName: "White Plains Beach	",location: "Kalaeloa"},
{beachName: "Nimitz Beach	K",location: "alaeloa"},
{beachName: "Barber's Point Beach Park",location: "Kalaeloa"}
];

const westShoreBeaches = [
{beachName: 'Ko Olina Beach Park	' , location: "Kalaeloa" },
{beachName: 'Lanikūhonua Beach	' , location: "Nānākuli" },
{beachName: 'Kahe Point Beach Park	' , location: "Nānākuli" },
{beachName: 'Tracks Beach Park (Hawaiian Electric Beach Park)	' , location: "Nānākuli" },
{beachName: 'Nānākuli Beach Park	' , location: "Nānākuli" },
{beachName: 'Ulehawa Beach Park	' , location: "Nānākuli" },
{beachName: 'Māʻili Beach Park	' , location: "Māʻili" },
{beachName: 'Lualualei Beach Park	' , location: "Waiʻanae" },
{beachName: 'Pōkaʻī Bay Beach	' , location: "Waiʻanae" },
{beachName: 'Waiʻanae Regional Park	' , location: "Waiʻanae" },
{beachName: 'Makana Beach Park	' , location: "Waiʻanae" },
{beachName: 'Mauna Lahilahi Beach Park	' , location: "Mākaha" },
{beachName: 'Turtle Beach	' , location: "Mākaha" },
{beachName: "Aki's Beach	" , location: "Mākaha" },
{beachName: 'Mākaha Beach Park	' , location: "Mākaha" },
{beachName: 'Keaʻau Beach Park	' , location: "Mākaha" },
{beachName: 'ʻŌhikilolo Beach	' , location: "Kaena Point" },
{beachName: 'Mākua Beach	' , location: "Kaena Point" },
{beachName: 'Keawaʻula Beach	' , location: "Kaena Point" },
{beachName: 'Kaʻena Point (Yokohama Bay)	' , location: "Kaena Point" }];


const eastShoreBeaches = [
{beachName: "Kahuku Golf Course Beach",	location: "Kahuku"},
{beachName: "Mālaekahana Beach",	location: "Kahuku"},
{beachName: "Mokuʻauia Beach",	location: "Kahuku"},
{beachName: "Hukilau Beach Park",	location: "Lāʻie"},
{beachName: "Temple Beach",	location: "Lāʻie"},
{beachName: "Lāʻie Beach",	location: "Lāʻie"},
{beachName: "Laniloa Beach",	location: "Lāʻie"},
{beachName: "Pounders Beach",	location: "Hauʻula"},
{beachName: "Kokololio Beach",	location: "Hauʻula"},
{beachName: "Kaipapaʻu Beach",	location: "Hauʻula"},
{beachName: "Hauʻula Beach Park",	location: "Hauʻula"},
{beachName: "Kaluanui Beach",	location: "Hauʻula"},
{beachName: "Punaluʻu Beach Park",	location: "Punaluʻu"},
{beachName: "Ahupuaʻa ʻO Kahana Bay Beach Park",	location: "Kaʻaʻawa"},
{beachName: "Makaua Beach Park",	location: "Kaʻaʻawa" },
{beachName: "Swanzy Beach Park",	location: "Kaʻaʻawa" },
{beachName: "Kaʻaʻawa Beach Park",	location: "Kaʻaʻawa" },
{beachName: "Kalaeʻōʻio Beach Park",	location: "Kaʻaʻawa" },
{beachName: "Secret Island",	location: "Waikāne" },
{beachName: "Kualoa Regional Park",	location: "Waikāne" },
{beachName: "Waiāhole Beach Park",	location: "Waiāhole" },
{beachName: "Kahaluʻu Regional Park",	location: "Kahaluʻu" },
{beachName: "Laenani Beach Park",	location: "Kahaluʻu" },
{beachName: "Heʻeia State Park",	location: "Heʻeia" },
{beachName: "Kāneʻohe Beach Park",	location: "Kāneʻohe" },
{beachName: "Marine Corps Base Hawaiʻi - Kāneʻohe Bay",	location: "Marine Corps Base Hawaiʻi" },
{beachName: "Kalama Beach",	location: "Kailua" },
{beachName: "Kailua Beach Park",	location: "Kailua" },
{beachName: "Lanikai Beach",	location: "Lanikai" },
{beachName: "Bellows Field Beach Park",	location: "Waimānalo Beach" },
{beachName: "Waimānalo Beach Park",	location: "Waimānalo Beach" },
{beachName: "Kaiona Beach Park",	location: "Waimānalo Beach" },
{beachName: "Kaupō Beach Park",	location: "Waimānalo Beach" },
{beachName: "Makapuʻu Beach Park",	location: "Makapuʻu"}
];

module.exports ={
	northShoreBeaches,
	southShoreBeaches,
	eastShoreBeaches,
	westShoreBeaches
}
